name: mini_widget
description: "Flutter base component package, For example InkCell, BlocProvider, etc."
version: 3.0.12
homepage: "https://github.com/collectFlutter/mini_widget.git"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  easy_refresh: ^3.4.0
  fluro: ^2.0.5
  material_design_icons_flutter: ^7.0.7296
  oktoast: ^3.4.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  flutter_bmflocation: ^3.6.0
  permission_handler: ^11.3.1
  mini_extension: ^3.0.0
  x5_webview: ^0.4.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
